title: Jack's Blog
SEOTitle: åšå®¢ | Jack Blog
header-img: "img/autumn2.jpg"
tagline: ""  
description: "Java å¼€å‘ ï½œ Golang å¼€å‘ & Service Mesh | è¿™é‡Œæ˜¯ @Jack çš„ä¸ªäººåšå®¢ğŸ’ª!"
url: "https://lqjack.github.io/"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
douban_username: lqjacklee
twitter_username: lqjacklee
github_username: lqjack
facebook_username: lqjacklee
weibo_username: lqjacklee
zhihu_username: lqjacklee


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 5
textColor: #FF0000
highlighter: rouge
paginate_path: "page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN

# Back to top å›åˆ°é¡¶éƒ¨by ray-eldath
b2t: true

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
gems: [jekyll-sitemap]



# About/contact
owner:
  name: "lqjack"
  email: lqjacklee@gmail.cn

# Data
gavatar: https://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge



# Netease settings
netease_comment: false


plugins:
- jekyll-gallery-generator
- jekyll-paginate
- jekyll-mermaid
- jekyll-sitemap
- jekyll-seo-tag

gitalk:
   enable: true
   owner: lqjack
   repo: lqjack.github.io
   clientID: a6589d87a7b777669521
   clientSecret: 5380e798fe628ba34f472dbf54515cf10f233f00
   admin: lqjack

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jack"
      header-img: "images/fantasy.jpg"

gallery:
  dir: images             # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    chile_trip:
      best_image: net.jpg  # The image to show on the gallery index page. Defaults to the last image.
    japan_trip:
      best_image: net.jpg
      name: "æ—¥æœ¬ã®æ—…"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
    awesome_stuff:
      best_image: mountain.jpg
      sort_reverse: true    # Reverse sort images in gallery.
    secret_stuff:
      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
    with_info:
      info:
        desc: "Gallery Description" # Info fields can be used in custom templates.

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-157817670-1'            # Format: UA-xxxxxx-xx
ga_domain: auto
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: â€œStash foolish , Stash hardğŸ’ª"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
	title: "Jack's Blog",
	href: "https://lqjack.github.io"
    }
]
